### ISSUE TITLE
Scraping stopped

### ISSUE THREAD

**Issue by IlianP** [lukebarousse/Data_Analyst_Streamlit_App_V1#9]
Just wanted to let you know that according to your https://datanerd.tech/Health,
It nearly stopped scraping jobs a few days ago.

**Comment by IlianP** [comment]
![visualization](https://github.com/lukebarousse/Data_Analyst_Streamlit_App_V1/assets/13310932/b1697725-9f5b-4b11-82b9-678fcca7ef22)

**Comment by lukebarousse** [comment]
Thanks for pointing this out! 

I looked into this, I'm currently scraping jobs within the past 24 hours from Google Search. I use the 24 hour period to get jobs posted from the previous day.  

However, it looks like [Google isn't populating jobs currently](https://www.google.com/search?q=data+analyst&oq=jobs+data+analyst&aqs=chrome.0.0i512l4j5j5i10i44j69i60l2.11114j0j7&sourceid=chrome&ie=UTF-8&ibp=htl;jobs&sa=X&ved=2ahUKEwig47Svh47_AhUNlmoFHR5aD4MQutcGKAF6BAgPEAY&sxsrf=APwXEdcW8P7KguZWphG2wWZZxP1T0XyiLw:1684934828575#fpstate=tldetail&htivrt=jobs&htichips=date_posted:today&htischips=date_posted;today&htilrad=-1.0) for this time requirement. 🤷🏼‍♂️

So I think this may be a bug (or new feature) with Google's job postings.  We'll have to wait and see if I need to readjust how I collect jobs.

Thanks again!

**Comment by lukebarousse** [comment]
Google started populating jobs again; thanks for noting this @IlianP 🙌🏼

<img width="751" alt="Screenshot 2023-05-25 at 8 17 08 AM" src="https://github.com/lukebarousse/Data_Analyst_Streamlit_App_V1/assets/44883645/7a58d2f8-2cff-4a89-8032-6aaace0fca1a">
